### ISSUE TITLE
Automate releases when committing to main

### ISSUE THREAD

**Issue by jkuester** [medic/cht-watchdog#34]
We should use semantic-release to automatically cut a release when a commit is merged to main instead of it being a manual process.

**Comment by m5r** [comment]
My understanding is that this CI job should automate the [release bits](https://github.com/medic/cht-monitoring/tree/update_dev_docs/development#development-process) in the docs. So when a commit is merged to main, it would create a new git branch following the new version `N.M.x` and create the `N.M.0` release in GitHub from the `N.M.x` branch.

I'm looking into how to deal with fixes. Ideally, `semantic-release` can pick up from a properly formatted commit message (i.e. `fix(foo): lorem ipsum`) whether it should cut a minor release or a patch release. I haven't found an answer yet but I'm planning to dig deeper into their docs and experiment with their CLI on a dummy repo before sharing an update here.

I believe `main` is protected, it means we can't push the version change in package.json from the CI job. `semantic-release`'s [recommended solution](https://semantic-release.gitbook.io/semantic-release/recipes/ci-configurations/github-actions#pushing-package.json-changes-to-a-master-branch) is less than ideal as it poses some security risks.  
I'm looking for an alternative and I will share an update here. In the meantime, I'm open to ideas/suggestions!

**Comment by jkuester** [comment]
For the sake of consistency, I think we should probably stick as close as possible to the patterns/config from cht-conf. (And if we find something we don't like about that config, we can look into updating the cht-conf config.)
