### ISSUE TITLE
Tweak alerting rules based off audit data

### ISSUE THREAD

**Issue by jkuester** [medic/cht-watchdog#35]
I audited the current alerts that are firing on https://allies-monitoring-alerting.dev.medicmobile.org/ and compiled [this speadsheet](https://docs.google.com/spreadsheets/d/1ZAHqPidHckvfQUoGdcE2AlPjiduC3A0kyUDNCBYTltw/edit?usp=sharing).

All in all the rule thresholds seem fairly reasonable. Most are being triggered on one or two instances, but not too much.  There are two alert rules, though, that need attention:

1. `DB Fragmentation`: This rule is firing a lot. It seems to primarily be a problem on smaller instances. I expect that with small DB sizes the fragmentation can be high (since CouchDB compaction [only runs for DBs > 1mb](https://docs.couchdb.org/en/stable/config/compaction.html#smoosh.{channel-name}/min_size).
    1. We should probably update the alert rule logic so that it does not trigger alerts for small DBs.... Maybe `< 1000 docs`.  (Especially since fragmentation is not actually a concern for smaller DBs)
2. `Message Delivery Rate`: This rule is sitting in the "No Data" status even when some of the instances tracked have data.  Need to review the config for the rule and figure out what is wrong.
3. `Client Feedback/Error Rate`: this rule right now just triggers if the rate is `> 4` regardless of how many users the CHT instance actually has.  We should scale the threshold based on instance size.

~Lastly, as a part of this ticket we should investigate the possibility of allowing these alert threshold values to be easily adjusted via configuration params (e.g. environment variables).~

**Comment by mrjones-plip** [comment]
> Lastly, as a part of this ticket we should investigate the possibility of allowing these alert threshold values to be easily adjusted via configuration params (e.g. environment variables).

ZOMG YES!

**Comment by mrjones-plip** [comment]
This is great - thanks for all the research @jkuester ! Good call to break the configuration effort out into #36.  We should be sure to document how it works today so that folks know how to tweak their alerts, even if we end up changing those docs when we work on #36.

**Comment by jkuester** [comment]
Yeah, @mrjones-plip, the sad part is that it does not really "work today".  The only options you have currently for customizing the alert thresholds are:

1. Manually edit the version-controlled config files to have your desired alerts
2. Remove the provisioned alerts (as hinted in the [docs](https://docs.communityhealthtoolkit.org/apps/guides/hosting/monitoring/setup/#alerts)) and create your own custom ones.

**Comment by mrjones-plip** [comment]
> Remove the provisioned alerts (as hinted in the [docs](https://docs.communityhealthtoolkit.org/apps/guides/hosting/monitoring/setup/#alerts)) and create your own custom ones.

Seems fine to me.  Are the downsides you went get updates to the alerts with future CMA releases?  Or maybe you have to re-remove them?

**Comment by jkuester** [comment]
> Are the downsides you wont get updates to the alerts with future CMA releases? Or maybe you have to re-remove them?

So the good thing is that you should not have to re-remove them, but the bad thing is that is because to actually remove them in the first place you have to add configuration to specifically remove them (specifying the alerts by UID).  I agree, though, that this is reasonable for the time being and I will add some formal documentation for how to do this!

**Comment by jkuester** [comment]
https://github.com/medic/cht-watchdog/pull/37
