### ISSUE TITLE
rename repo to cht-watchdog

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-watchdog#41]
We decided that `cht-monitoring` or `CHT Monitoring and Alerting` or `CMA` didn't focus on the key functionality of "Alerting" enough.  As such, [we rebranded](https://medic.slack.com/archives/C02FMC810UE/p1683150490050659) (private slack link) to `CHT Watchdog` and we'd like change the repo name.

@jkuester, given you may have a bunch of changes queued that we don't want to lose,  can you schedule this change in the coming week or so?  You'll likely need to work with @garethbowen  or another GH admin.  I believe steps will be:
1. schedule and announce change in #product-allies and #app-monitoring
2. execute change at scheduled time
3. alert folks how to follow the change by editing `.git/config` so that `url = git@github.com:medic/cht-monitoring.git` is changed to `url = git@github.com:medic/cht-watchdog.git`

**Comment by mrjones-plip** [comment]
noting that I wrote "in the coming day" when I meant "in the coming week or so" - no real rush!

**Comment by m5r** [comment]
I wonder if step 3 is mandatory. I believe GitHub redirects any traffic from `$oldRepo` to `$newRepo` automatically

**Comment by mrjones-plip** [comment]
Ah - cool cool - thanks @m5r !  I knew it redirected HTTP traffic but wasn't sure about SSH

**Comment by mrjones-plip** [comment]
Perfect - thanks for testing @m5r !

**Comment by mrjones-plip** [comment]
@kennsippell did the deed today - thank you!!

**Comment by m5r** [comment]
Thanks!

GitHub does redirect from `cht-monitoring` but if this message is bothering you

```
remote: This repository moved. Please use the new location:
remote:   git@github.com:medic/cht-watchdog.git
```

you can run this command to update the origin url `git remote set-url origin git@github.com:medic/cht-watchdog.git`
