### ISSUE TITLE
DB Fragmentation Alert: remove or tie to other metric

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-watchdog#45]
There is [an alert "DB Fragmentation"](https://github.com/medic/cht-watchdog/blob/b75042536a8f6163bd4f9aa092cc3cadd90b21c8/grafana/provisioning/alerting/cht.yml#L9) that currently fires quite a bit on our test instance.  We should either tie this to another metric where logical (eg active users >500?  I don't know), or remove it all together.  It is otherwise inaction-able. 

------

[[FIRING:28] DB Fragmentation CHT (cht)](https://allies-monitoring-alerting.dev.medicmobile.org/alerting/list)
**Firing**Value: B=27.055714740528494, C=1
Labels:
- alertname = DB Fragmentation
- db = _users
- grafana_folder = CHT
- instance = [INSTANCE-NAME.app.medicmobile.org](http://INSTANCE-NAME.app.medicmobile.org/)
- job = cht
Annotations:
- description = The [_users] database for the CHT Server [[INSTANCE-NAME.app.medicmobile.org](http://INSTANCE-NAME.app.medicmobile.org/)] is highly fragmented.

**Comment by jkuester** [comment]
I believe the frequency of this alert was addressed in https://github.com/medic/cht-watchdog/issues/35.  We updated the config to only alert if the DB as `> 1000` docs.

**Comment by mrjones-plip** [comment]
Cools - thanks @jkuester ! let's close this then and see how we do with `1.2.0` on prod.
