### ISSUE TITLE
Instance-less "DatasourceNoData" should be removed

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-watchdog#51]
There is an alert firing for `DatasourceNoData CHT`   (see [example](https://medic.slack.com/archives/C057BCEG9EH/p1684185213421749)) that seems to not be affiliated with any instance so is not actionable.  This alert should be removed.

**Comment by m5r** [comment]
I'm not sure if it's not affiliated with any instance or if the data source is wrong and cannot map to the instance that raises this alert

**Comment by m5r** [comment]
As [discussed in slack](https://medic.slack.com/archives/C02FMC810UE/p1684414873435439), restarting the containers have fixed the issue: the message delivery alert now matches with each instance and the alerts in slack have stopped

I'll close this issue but let's keep an eye out for these alerts behave next time we upgrade our watchdog instance
