### ISSUE TITLE
Add supported method for deleting provisioned alerts

### ISSUE THREAD

**Issue by jkuester** [medic/cht-watchdog#53]
Currently the [documentation](https://docs.communityhealthtoolkit.org/apps/guides/hosting/monitoring/setup/#alerts) links to some Grafana docs regarding how to actually modify/delete the provisioned alert rules.  Unfortunately, it is mostly up to the user to figure out how to do that.  

Since modifying/deleting provisioned alerts is likely to be a common customization, we should provide a recommended approach and then document it.

**Comment by mrjones-plip** [comment]
Possibly related to #49
