### ISSUE TITLE
Collect metrics about CHT endpoint performance

### ISSUE THREAD

**Issue by jkuester** [medic/cht-watchdog#60]
From @garethbowen's [Slack message](https://medic.slack.com/archives/C02FMC810UE/p1686537518108469):

> I came across this [express.js prometheus middleware](https://www.npmjs.com/package/express-prometheus-middleware) that collects response status and duration information which might be a really clean way to monitor performance of certain endpoints (eg: replication) without doing much bespoke development.

**Comment by kennsippell** [comment]
This does look clean. Is there also a plan to bring log data into Grafana?  If that work is already being done, the response_time and status are in the medic-api logs and it may be straightforward to bring that into Grafana. Does anybody have experience with these? Does anybody have a preference for the approach used?

**Comment by jkuester** [comment]
We have had some long-term discussions about the possibility of bringing in log data (via something like Loki)! It is not the top of the list of priorities, but is definitely something that would be valuable and folks have already shown interest in.

**Comment by garethbowen** [comment]
We definitely want to improve logging, particularly for self-hosted installs, which may be Loki+Grafana. The downside to that is it exposes PHI where there wasn't before so it may not be the right approach. I've heard mixed feedback about it, but interestingly MoH Kenya are using it for other services and they like it and might be the ideal candidate for evaluating our approach.

Looking at one of the demo videos for Loki it can pull out response times and failure rates for different endpoints so it would also do what we need. Definitely worth investigating as well as any other options to do the same thing.

**Comment by kennsippell** [comment]
### joao-fontenele/express-prometheus-middleware 
https://github.com/joao-fontenele/express-prometheus-middleware 

* I fear the package may be end of life. I can't find any official announcement, but the repository has been archived and no updates in 2 years. I asked about the project's future [here](https://app.gitter.im/#/room/#express-prometheus-middleware_community:gitter.im) and await a response. 
* Under the hood, this project exclusively uses the [response-time library](https://www.npmjs.com/package/response-time) which records "... the elapsed time from when a request enters this middleware to when the headers are written". The time reported for `_changes` requests is the heartbeat time (always 10 seconds) and so this library can't be used to monitor the performance of offline user replication. 
* Very useful interface _extraMasks_ interface for grouping endpoints. It is really useful to differential similar routes (like offline _changes requests vs longpoll) and group requests (like `/medic/resources/*`, or `/medic/{uuid}`) for meaningful monitoring by endpoint. No other library below supports something like this. 
* The [importable dashboard](https://grafana.com/grafana/dashboards/14565-node-js-dashboard/) is definitely the best available - even just its presentation of the prom-client standard metrics. 

### matteodisabatino/express-prometheus-middleware 
https://github.com/matteodisabatino/express-prometheus-middleware 

Official option on the Grafana site. Very basic with poor extensibility. No segmentation of metrics by endpoint at all. I don't think we should consider this. 

### prometheus-api-metrics 
https://github.com/PayU/prometheus-api-metrics 
* Stewarded by PayU.com a global payment provider. 
* This reports time from request to response [finished](https://github.com/PayU/prometheus-api-metrics/blob/master/src/express-middleware.js#L121) so this should accurately report offline user _changes requests. 
* Routes are grouped by the express route (eg. /+medic/+:docId/{0,}) and not the path (like express-prometheus-middleware). I like it, but some issues with CHT requests (eg. resources are not properly grouped). No support for differentiating routes or custom grouping. I personally feel it is really important to monitor longpoll _changes requests differently from offline user _changes requests during replication.  
* [The premade dashboards](https://grafana.com/grafana/dashboards/12230-node-js-dashboard/) are decent for GC stuff but seem way worse than joao-fontenele for request duration. I can try to combine them? 
* Good support [for custom metrics](https://github.com/PayU/prometheus-api-metrics#custom-metrics) through prom-client, so we have custom metrics like yield or replication yield as first-class citizens in CHT monitoring. 

### prom-client 
https://github.com/siimon/prom-client 

* Under the hood all these projects use prom-client.  
* A lot of the process/GC metrics by default. 

### Recommendation 

Short-List of Tooling Options 
* Use prometheus-api-metrics and contribute a feature to improve route differentiation/grouping 
* Custom implementation based on prom-client  
* Implementation based on logs

Recommendations 
* Reuse the express-prometheus-middleware dashboards 
* Look into contributing the needed feature to prometheus-api-metrics and rely on prom-client if that doesn't go well for whatever reason

**Comment by garethbowen** [comment]
Great write up, thanks!

One thing to consider is assuming this requires a cht-core api code change, then it'll presumably be released in 4.3.0 and not backported to previous versions. If so, then the endpoints to monitor will change completely with the [new replication algorithm](https://github.com/medic/cht-core/issues/8296). This means the _changes endpoint likely no longer needs to be monitored, which in turn means the issues you've cited with longpoll, heartbeat, etc should not be a problem.

**Comment by kennsippell** [comment]
True. My thinking is _so_ 4.2.

**Comment by dianabarsan** [comment]
> there is no heartbeat or anything similarly affecting time-to-first-byte in 4.3 replication requests

This is correct, _changes endpoint will no longer be used as of 4.3. We still need endpoint filtering, even if we're changing the protocol, we will still have at least one resource intensive endpoint - but these endpoints will less likely be shared between use-cases (there won't be a "longpoll" variant to be ignored for example). 

I trust PayU, they are very big in Europe.

**Comment by kennsippell** [comment]
I like PayU's focus of [Apdex](https://en.wikipedia.org/wiki/Apdex). Pretty cool.

With the PayU lib, we get a bunch of noisy routes from our default route.  It records unique routes per path instead of grouping things that hit the default route together.  Here are some paths affected with _local docs and resources being the noisiest. 

* /medic/
* /medic/resources/* 
* /medic/branding/* 
* /*-users-meta/ 
* /*-users-meta/_local* 
* /*-users-meta/_rev_diff 
* /*-users-meta/_design/* 
* /*-users-meta/_bulk_docs 
* …. probably more I don't know about 

![image](https://github.com/medic/cht-watchdog/assets/9014751/78848d9f-a916-4571-8ff3-aec983c2d33e)

I've made a PR to fix that [here](https://github.com/PayU/prometheus-api-metrics/issues/112).  

I'm also investigating a [second issue](https://github.com/PayU/prometheus-api-metrics/issues/114) which is causing a different pattern of noise. This seems less critical, but would be nice.

With the PayU library, all requests for static content (service-worker.js, runtime.js, etc.) are grouped together under a route called "N/A" because of our use of `app.use(express.static());`. I haven't filed a bug for this because I don't know how I'd go about fixing it exactly.  I can't find anything else which triggers this reporting behavior.
