### ISSUE TITLE
CHT Replication Dashboard - Apdex is not properly constrained to selected interval

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-watchdog#90]
We are getting some realistic data for ApDex now that this is live. Here is a set of slow replication latencies. 
![image](https://github.com/medic/cht-watchdog/assets/9014751/a9442eee-b748-4d13-a8a6-9efadfe25891)

The apdex for the period is 94%, but the graph for the duration shows nearly 100% for the full duration.
Changing the timescale for the graph doesn't alter either apdex score.

**Comment by jkuester** [comment]
@kennsippell can this issue be closed now?
